import type { SavedView } from "@/components/queue/saved-views-manager"

export const defaultSavedViews: SavedView[] = [
  {
    id: "my-queue",
    name: "My Queue",
    filters: { assignedTo: "current_user" },
    isPinned: true,
    isDefault: true,
    isSystem: true,
    incidentCount: 12,
  },
  {
    id: "open",
    name: "Open Incidents",
    filters: { status: ["new", "assigned", "in-progress"] },
    isPinned: true,
    isDefault: false,
    isSystem: true,
    incidentCount: 42,
  },
  {
    id: "critical",
    name: "Critical Incidents",
    filters: { priority: ["critical"] },
    isPinned: true,
    isDefault: false,
    isSystem: true,
    incidentCount: 5,
  },
  {
    id: "sla-breach",
    name: "SLA Breaches",
    filters: { slaState: ["breached", "breach"] },
    isPinned: true,
    isDefault: false,
    isSystem: true,
    incidentCount: 8,
  },
  {
    id: "escalated",
    name: "Escalated",
    filters: { status: ["escalated"] },
    isPinned: false,
    isDefault: false,
    isSystem: true,
    incidentCount: 5,
  },
  {
    id: "vip",
    name: "VIP Incidents",
    filters: { tags: ["VIP"] },
    isPinned: false,
    isDefault: false,
    isSystem: true,
    incidentCount: 3,
  },
  {
    id: "recently-updated",
    name: "Recently Updated",
    filters: { updatedAt: "last_24h" },
    isPinned: false,
    isDefault: false,
    isSystem: true,
    incidentCount: 67,
  },
  {
    id: "major-incidents",
    name: "Major Incidents",
    filters: { status: ["major-incident"] },
    isPinned: false,
    isDefault: false,
    isSystem: true,
    incidentCount: 2,
  },
  {
    id: "unassigned",
    name: "Unassigned",
    filters: { assignedTo: null },
    isPinned: false,
    isDefault: false,
    isSystem: true,
    incidentCount: 15,
  },
  {
    id: "high-priority",
    name: "High Priority",
    filters: { priority: ["critical", "high"] },
    isPinned: false,
    isDefault: false,
    isSystem: false,
    incidentCount: 23,
  },
]
